FROM node:18-alpine
WORKDIR /usr/app
COPY ./ /usr/app

ARG EXPOSE_PORT=3000
ARG SYSTEM_ENV="DEV"
ARG DATABASE_URL="postgresql://postgres:exmaple@localhost:5432/log"
ENV SYSTEM_PORT=${EXPOSE_PORT}
ENV LDATABASE_URL=${DATABASE_URL}
ENV SYSTEM_ENVIORMENT=${SYSTEM_ENV}
RUN npm install
EXPOSE ${EXPOSE_PORT}
CMD ["npm", "start"]