FROM node:18
WORKDIR /app
COPY package*.js ./
RUN npm install
COPY . .

ARG AUTH_TOKEN_PRIVATE_REGISTRY
ARG EXPOSE_PORT
ENV SERVER_PORT = ${SERVER_PORT}
ENV NPM_TOKEN=${AUTH_TOKEN_PRIVATE_REGISTRY}
EXPOSE ${EXPOSE_PORT}
CMD ["npm", "start"]